# это осталось от прокси - событие обновления контракта
type Upgraded @entity(immutable: true) {
  id: Bytes!
  implementation: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
# событие создания новой кампании
type FVCampaignCreated @entity(immutable: true) {
  id: Bytes!
  newCampaignAddress: CampaignData! # newCampaignAddress: Bytes! # address
  founder: Bytes! # address
  token: Bytes! # address
  goal: BigInt! # uint256  
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!              
}
# сущности кампаний
type CampaignData @entity(immutable: false) {  
  id: Bytes! # address - адрес кампании
  campaignId: BigInt! # id кампании
  creator: Bytes! # address  
  goal: BigInt! # uint256
  raised: BigInt! # uint128
  deadline: BigInt! # uint32
  token: Bytes! # address
  campaignMeta: String!
  status: Int! # Status(uint8)
  # из событий кампании
  isFundsWithdrawn: Boolean! # признак, выведены ли фонды
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!              
}

#Токены
# событие добавления токена
type FVNewTokenAdded @entity(immutable: true) {
  id: Bytes!
  token: Token! # address      
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!  
}

# событие удаления токена
type FVTokenRemoved @entity(immutable: true) {
  id: Bytes!
  token: Token! # address
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!  
}

# сущность токена
type Token @entity(immutable: false) {  
  id: Bytes! # address - первичный ключ - адрес токена
  symbol: String!
  decimals: Int!
  name: String!
  status: Boolean!
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!  
}

# события кампании
# поступление взноса
type CampaignContribution @entity(immutable: true) {
  id: Bytes!
  contributor: Bytes! # address
  amount: BigInt! # uint256
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

# вывод собранных средств
type CampaignFundsClaimed @entity(immutable: true) {
  id: Bytes!
  recipient: Bytes! # address
  amount: BigInt! # uint256
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}