# это осталось от прокси - событие обновления контракта
type Upgraded @entity(immutable: true) {
  id: Bytes!
  implementation: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
# событие создания новой кампании
type FVCampaignCreated @entity(immutable: true) {
  id: Bytes!
  newCampaignAddress: Bytes! # address
  founder: Bytes! # address
  token: Bytes! # address
  goal: BigInt! # uint256  
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!              
}
# сущности кампаний
type CampaignData @entity(immutable: false) {  
  id: Bytes! # address - адрес кампании
  founder: Bytes! # address
  token: Bytes! # address
  goal: BigInt! # uint256
  # поля, загружаемые из кампании
  capmpaignId: BigInt! # id кампании
  raised: BigInt! # uint128
  deadline: BigInt! # uint32
  campaignMeta: String
  status: Int # Status(uint8)
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!              
}

# событие добавления токена
type FVNewTokenAdded @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address    
  #symbol: string;
  #decimals: number;
  #name: string;
  #status: boolean;"  
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!  
}

# событие удаления токена
type FVTokenRemoved @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!  
}

# события кампании
# поступление взноса
type CampaignContribution @entity(immutable: true) {
  id: Bytes!
  contributor: Bytes! # address
  amount: BigInt! # uint256
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

# вывод собранных средств
type CampaignFundsClaimed @entity(immutable: true) {
  id: Bytes!
  recipient: Bytes! # address
  amount: BigInt! # uint256
  # данные блока
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}